"""Initial

Revision ID: 0db51fd66913
Revises: 
Create Date: 2025-08-08 17:15:33.987826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db51fd66913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('coordenador_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('meta_facilitadores_treinamento', sa.Integer(), nullable=True),
    sa.Column('meta_anfitrioes_treinamento', sa.Integer(), nullable=True),
    sa.Column('meta_ctm_participantes', sa.Integer(), nullable=True),
    sa.Column('meta_encontro_deus_participantes', sa.Integer(), nullable=True),
    sa.Column('meta_batizados_aclamados', sa.Integer(), nullable=True),
    sa.Column('meta_multiplicacoes_pg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordenador_id'], ['membro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('pequeno_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('facilitador_id', sa.Integer(), nullable=False),
    sa.Column('anfitriao_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('dia_reuniao', sa.String(length=20), nullable=False),
    sa.Column('horario_reuniao', sa.String(length=10), nullable=False),
    sa.Column('data_multiplicacao', sa.DateTime(), nullable=True),
    sa.Column('meta_facilitadores_treinamento', sa.Integer(), nullable=True),
    sa.Column('meta_anfitrioes_treinamento', sa.Integer(), nullable=True),
    sa.Column('meta_ctm_participantes', sa.Integer(), nullable=True),
    sa.Column('meta_encontro_deus_participantes', sa.Integer(), nullable=True),
    sa.Column('meta_batizados_aclamados', sa.Integer(), nullable=True),
    sa.Column('meta_multiplicacoes_pg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anfitriao_id'], ['membro.id'], ),
    sa.ForeignKeyConstraint(['facilitador_id'], ['membro.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('meta_facilitadores_treinamento', sa.Integer(), nullable=True),
    sa.Column('meta_anfitrioes_treinamento', sa.Integer(), nullable=True),
    sa.Column('meta_ctm_participantes', sa.Integer(), nullable=True),
    sa.Column('meta_encontro_deus_participantes', sa.Integer(), nullable=True),
    sa.Column('meta_batizados_aclamados', sa.Integer(), nullable=True),
    sa.Column('meta_multiplicacoes_pg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['membro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('jornada_area_associacao',
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada_evento.id'], ),
    sa.PrimaryKeyConstraint('jornada_id', 'area_id')
    )
    op.create_table('jornada_membro_associacao',
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada_evento.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['membro.id'], ),
    sa.PrimaryKeyConstraint('jornada_id', 'membro_id')
    )
    op.create_table('jornada_pg_associacao',
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('pequeno_grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada_evento.id'], ),
    sa.ForeignKeyConstraint(['pequeno_grupo_id'], ['pequeno_grupo.id'], ),
    sa.PrimaryKeyConstraint('jornada_id', 'pequeno_grupo_id')
    )
    op.create_table('jornada_setor_associacao',
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornada_evento.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('jornada_id', 'setor_id')
    )
    with op.batch_alter_table('jornada_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_executor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_acao', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('descricao_detalhada', sa.Text(), nullable=False))
        batch_op.alter_column('data_evento',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_jornada_evento_usuario_executor_id_user', 'user', ['usuario_executor_id'], ['id'])
        batch_op.drop_column('membro_id')
        batch_op.drop_column('tipo_evento')
        batch_op.drop_column('descricao')

    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_recepcao', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('obs_recepcao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pg_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_treinamento_pg', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('participou_ctm', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('participou_encontro_deus', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('batizado_aclamado', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('campus_frequencia', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_membro_pg_id_pequeno_grupo', 'pequeno_grupo', ['pg_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('permissions', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('membro_id', sa.Integer(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['membro_id'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key('fk_user_membro_id_membro', 'membro', ['membro_id'], ['id'])
        batch_op.drop_column('username')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='unique')
        # batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('membro_id')
        batch_op.drop_column('permissions')
        batch_op.drop_column('email')

    with op.batch_alter_table('membro', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campus_frequencia')
        batch_op.drop_column('batizado_aclamado')
        batch_op.drop_column('participou_encontro_deus')
        batch_op.drop_column('participou_ctm')
        batch_op.drop_column('status_treinamento_pg')
        batch_op.drop_column('pg_id')
        batch_op.drop_column('obs_recepcao')
        batch_op.drop_column('tipo_recepcao')

    with op.batch_alter_table('jornada_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('tipo_evento', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('membro_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_jornada_evento_membro_id_membro', 'membro', ['membro_id'], ['id'])
        batch_op.alter_column('data_evento',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('descricao_detalhada')
        batch_op.drop_column('tipo_acao')
        batch_op.drop_column('usuario_executor_id')

    op.drop_table('jornada_setor_associacao')
    op.drop_table('jornada_pg_associacao')
    op.drop_table('jornada_membro_associacao')
    op.drop_table('jornada_area_associacao')
    op.drop_table('setor')
    op.drop_table('pequeno_grupo')
    op.drop_table('area')
    # ### end Alembic commands ###
