"""Preparação para atualização

Revision ID: 2a950d0ecbc5
Revises: 0db51fd66913
Create Date: 2025-08-08 17:20:08.428836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a950d0ecbc5'
down_revision = '0db51fd66913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Criando tabelas com nomes de restrição e ordem correta
    op.create_table('area',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=80), nullable=False),
        sa.Column('coordenador_id', sa.Integer(), nullable=False),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('meta_facilitadores_treinamento', sa.Integer(), nullable=True),
        sa.Column('meta_anfitrioes_treinamento', sa.Integer(), nullable=True),
        sa.Column('meta_ctm_participantes', sa.Integer(), nullable=True),
        sa.Column('meta_encontro_deus_participantes', sa.Integer(), nullable=True),
        sa.Column('meta_batizados_aclamados', sa.Integer(), nullable=True),
        sa.Column('meta_multiplicacoes_pg', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['coordenador_id'], ['membro.id'], name='fk_area_coordenador_id_membro'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome', name='uq_area_nome')
    )
    op.create_table('setor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=80), nullable=False),
        sa.Column('supervisor_id', sa.Integer(), nullable=False),
        sa.Column('area_id', sa.Integer(), nullable=False),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('meta_facilitadores_treinamento', sa.Integer(), nullable=True),
        sa.Column('meta_anfitrioes_treinamento', sa.Integer(), nullable=True),
        sa.Column('meta_ctm_participantes', sa.Integer(), nullable=True),
        sa.Column('meta_encontro_deus_participantes', sa.Integer(), nullable=True),
        sa.Column('meta_batizados_aclamados', sa.Integer(), nullable=True),
        sa.Column('meta_multiplicacoes_pg', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['area_id'], ['area.id'], name='fk_setor_area_id_area'),
        sa.ForeignKeyConstraint(['supervisor_id'], ['membro.id'], name='fk_setor_supervisor_id_membro'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome', name='uq_setor_nome')
    )
    op.create_table('pequeno_grupo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('facilitador_id', sa.Integer(), nullable=False),
        sa.Column('anfitriao_id', sa.Integer(), nullable=False),
        sa.Column('setor_id', sa.Integer(), nullable=False),
        sa.Column('dia_reuniao', sa.String(length=20), nullable=False),
        sa.Column('horario_reuniao', sa.String(length=10), nullable=False),
        sa.Column('data_multiplicacao', sa.DateTime(), nullable=True),
        sa.Column('meta_facilitadores_treinamento', sa.Integer(), nullable=True),
        sa.Column('meta_anfitrioes_treinamento', sa.Integer(), nullable=True),
        sa.Column('meta_ctm_participantes', sa.Integer(), nullable=True),
        sa.Column('meta_encontro_deus_participantes', sa.Integer(), nullable=True),
        sa.Column('meta_batizados_aclamados', sa.Integer(), nullable=True),
        sa.Column('meta_multiplicacoes_pg', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['anfitriao_id'], ['membro.id'], name='fk_pequenogrupo_anfitriao_id_membro'),
        sa.ForeignKeyConstraint(['facilitador_id'], ['membro.id'], name='fk_pequenogrupo_facilitador_id_membro'),
        sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], name='fk_pequenogrupo_setor_id_setor'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome', name='uq_pequenogrupo_nome')
    )
    op.create_table('jornada_area_associacao',
        sa.Column('jornada_id', sa.Integer(), nullable=False),
        sa.Column('area_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['area_id'], ['area.id'], name='fk_jornada_area_associacao_area_id'),
        sa.ForeignKeyConstraint(['jornada_id'], ['jornada_evento.id'], name='fk_jornada_area_associacao_jornada_id'),
        sa.PrimaryKeyConstraint('jornada_id', 'area_id')
    )
    op.create_table('jornada_membro_associacao',
        sa.Column('jornada_id', sa.Integer(), nullable=False),
        sa.Column('membro_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['jornada_id'], ['jornada_evento.id'], name='fk_jornada_membro_associacao_jornada_id'),
        sa.ForeignKeyConstraint(['membro_id'], ['membro.id'], name='fk_jornada_membro_associacao_membro_id'),
        sa.PrimaryKeyConstraint('jornada_id', 'membro_id')
    )
    op.create_table('jornada_pg_associacao',
        sa.Column('jornada_id', sa.Integer(), nullable=False),
        sa.Column('pequeno_grupo_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['jornada_id'], ['jornada_evento.id'], name='fk_jornada_pg_associacao_jornada_id'),
        sa.ForeignKeyConstraint(['pequeno_grupo_id'], ['pequeno_grupo.id'], name='fk_jornada_pg_associacao_pequeno_grupo_id'),
        sa.PrimaryKeyConstraint('jornada_id', 'pequeno_grupo_id')
    )
    op.create_table('jornada_setor_associacao',
        sa.Column('jornada_id', sa.Integer(), nullable=False),
        sa.Column('setor_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['jornada_id'], ['jornada_evento.id'], name='fk_jornada_setor_associacao_jornada_id'),
        sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], name='fk_jornada_setor_associacao_setor_id'),
        sa.PrimaryKeyConstraint('jornada_id', 'setor_id')
    )
    with op.batch_alter_table('jornada_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_executor_id', sa.Integer(), nullable=True))
        # Correção 1: Adiciona 'server_default' para evitar IntegrityError em colunas NOT NULL
        batch_op.add_column(sa.Column('tipo_acao', sa.String(length=100), nullable=False, server_default='sem_acao'))
        # Correção 2: Adiciona 'server_default' para evitar IntegrityError em colunas NOT NULL
        batch_op.add_column(sa.Column('descricao_detalhada', sa.Text(), nullable=False, server_default='sem_descricao'))
        batch_op.alter_column('data_evento',
               existing_type=sa.DATETIME(),
               nullable=False)
        # Linha comentada para evitar erros de restrição sem nome, conforme orientado
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_jornada_evento_usuario_executor_id_user', 'user', ['usuario_executor_id'], ['id'])
        batch_op.drop_column('membro_id')
        batch_op.drop_column('descricao')
        batch_op.drop_column('tipo_evento')
    
    # Remover os valores padrão após a migração para novas entradas
    with op.batch_alter_table('jornada_evento', schema=None) as batch_op:
        batch_op.alter_column('tipo_acao', server_default=None)
        batch_op.alter_column('descricao_detalhada', server_default=None)

    with op.batch_alter_table('membro', schema=None) as batch_op:
        # Correção 3: Adiciona 'server_default' para evitar IntegrityError em colunas NOT NULL
        batch_op.add_column(sa.Column('tipo_recepcao', sa.String(length=50), nullable=False, server_default='membro'))
        batch_op.add_column(sa.Column('obs_recepcao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pg_id', sa.Integer(), nullable=True))
        # Correção 4: Adiciona 'server_default' para evitar IntegrityError em colunas NOT NULL
        batch_op.add_column(sa.Column('status_treinamento_pg', sa.String(length=50), nullable=False, server_default='nao_treinado'))
        # Correção 5: Adiciona 'server_default' para evitar IntegrityError em colunas NOT NULL
        batch_op.add_column(sa.Column('participou_ctm', sa.Boolean(), nullable=False, server_default='False'))
        # Correção 6: Adiciona 'server_default' para evitar IntegrityError em colunas NOT NULL
        batch_op.add_column(sa.Column('participou_encontro_deus', sa.Boolean(), nullable=False, server_default='False'))
        # Correção 7: Adiciona 'server_default' para evitar IntegrityError em colunas NOT NULL
        batch_op.add_column(sa.Column('batizado_aclamado', sa.Boolean(), nullable=False, server_default='False'))
        batch_op.add_column(sa.Column('campus_frequencia', sa.String(length=50), nullable=True))
        # Linha comentada para evitar erros de restrição sem nome
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_membro_pg_id_pequeno_grupo', 'pequeno_grupo', ['pg_id'], ['id'])
    
    # Remover os valores padrão após a migração para novas entradas
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.alter_column('tipo_recepcao', server_default=None)
        batch_op.alter_column('status_treinamento_pg', server_default=None)
        batch_op.alter_column('participou_ctm', server_default=None)
        batch_op.alter_column('participou_encontro_deus', server_default=None)
        batch_op.alter_column('batizado_aclamado', server_default=None)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False, server_default='email_padrao@exemplo.com'))
        batch_op.add_column(sa.Column('permissions', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('membro_id', sa.Integer(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_membro_id', ['membro_id'])
        # Linha comentada para evitar erros de restrição sem nome
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user_membro_id_membro', 'membro', ['membro_id'], ['id'])
        batch_op.drop_column('role')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Bloco downgrade ajustado para evitar erros de remoção de restrições
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False, server_default='default_user'))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_user_membro_id_membro', type_='foreignkey')
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_membro_id', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('membro_id')
        batch_op.drop_column('permissions')
        batch_op.drop_column('email')

    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.drop_constraint('fk_membro_pg_id_pequeno_grupo', type_='foreignkey')
        batch_op.drop_column('campus_frequencia')
        batch_op.drop_column('batizado_aclamado')
        batch_op.drop_column('participou_encontro_deus')
        batch_op.drop_column('participou_ctm')
        batch_op.drop_column('status_treinamento_pg')
        batch_op.drop_column('pg_id')
        batch_op.drop_column('obs_recepcao')
        batch_op.drop_column('tipo_recepcao')

    with op.batch_alter_table('jornada_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_evento', sa.VARCHAR(length=50), nullable=False, server_default='default_evento'))
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), nullable=False, server_default='default_descricao'))
        batch_op.add_column(sa.Column('membro_id', sa.INTEGER(), nullable=False, server_default='1'))
        batch_op.drop_constraint('fk_jornada_evento_usuario_executor_id_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_jornada_evento_membro_id_membro', 'membro', ['membro_id'], ['id'])
        batch_op.alter_column('data_evento',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('descricao_detalhada')
        batch_op.drop_column('tipo_acao')
        batch_op.drop_column('usuario_executor_id')
    
    op.drop_table('jornada_setor_associacao')
    op.drop_table('jornada_pg_associacao')
    op.drop_table('jornada_membro_associacao')
    op.drop_table('jornada_area_associacao')
    op.drop_table('pequeno_grupo')
    op.drop_table('setor')
    op.drop_table('area')
    # ### end Alembic commands ###