"""Atualização de valores nulos

Revision ID: 396fd74b70c8
Revises: b293ddeadbab
Create Date: 2025-08-11 17:56:32.114961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396fd74b70c8'
down_revision = 'b293ddeadbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.alter_column('tipo_recepcao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.alter_column('tipo_recepcao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
