"""Adicionar campos de membro e permissoes ao User

Revision ID: 7233ecbd73e6
Revises: 7ce7ef2378cc
Create Date: 2025-07-10 19:10:29.545156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7233ecbd73e6'
down_revision = '7ce7ef2378cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('turma') # REMOVIDO/COMENTADO
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False, server_default='temp@example.com'))
        batch_op.add_column(sa.Column('permissions', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('membro_id', sa.Integer(), nullable=True))
        batch_op.alter_column('password_hash',
                            existing_type=sa.VARCHAR(length=128),
                            type_=sa.String(length=256),
                            existing_nullable=False)
        batch_op.create_unique_constraint('uq_user_membro_id', ['membro_id'])
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_foreign_key('fk_user_membro_id', 'membro', ['membro_id'], ['id'])
        batch_op.drop_column('username')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email', existing_type=sa.String(length=120), server_default=sa.text("'temp@example.com'"), existing_nullable=False)

        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint('fk_user_membro_id', type_='foreignkey')
        batch_op.drop_constraint('uq_user_membro_id', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

        batch_op.alter_column('password_hash',
                            existing_type=sa.String(length=256),
                            type_=sa.VARCHAR(length=128),
                            existing_nullable=False)
        batch_op.drop_column('membro_id')
        batch_op.drop_column('permissions')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
