"""Atualização de modelo de membro

Revision ID: b293ddeadbab
Revises: 2a950d0ecbc5
Create Date: 2025-08-11 17:06:03.203268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b293ddeadbab'
down_revision = '2a950d0ecbc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.drop_column('campus_frequencia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_frequencia', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
